service: serverless-graphql-rest

frameworkVersion: "2"

provider:
  name: "aws"
  runtime: "nodejs12.x"
  region: "eu-west-1"

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    includeModules: true
  webpackIncludeModules: true

functions:
  graphql:
    handler: handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
